/* Ember Tobacco Co. — catalogue (Manchester range + Seven Stars).
 * Prices indicative only. Product photos in assets/products/<id>.png */
window.EMBER_PRODUCTS = [
  { id: 'man-sapphire', brand: 'Manchester', name: 'Sapphire 16mc', cat: 'cigarettes', style: 'regular', price: 38.95,                          rating: 4.7, ratingCount: 18, unit: 'per pack', stock: 'instock',                  accent: 'var(--blue-400)',  image: 'assets/products/man-sapphire.png' },
  { id: 'man-royal',    brand: 'Manchester', name: 'Royal 16mc',    cat: 'cigarettes', style: 'regular', price: 38.95, oldPrice: 44.95, discount: '13% OFF', rating: 4.8, ratingCount: 24, unit: 'per pack', stock: 'instock', flag: 'Popular',  accent: 'var(--ember-500)', image: 'assets/products/man-royal.png' },
  { id: 'man-special',  brand: 'Manchester', name: 'Special 10mc',  cat: 'cigarettes', style: 'regular', price: 36.95,                          rating: 4.6, ratingCount: 12, unit: 'per pack', stock: 'low',                      accent: 'var(--gold-500)',  image: 'assets/products/man-special.png' },
  { id: 'man-green',    brand: 'Manchester', name: 'Green Crush 6mc', cat: 'cigarettes', style: 'menthol', price: 39.95, oldPrice: 45.95, discount: '13% OFF', rating: 4.9, ratingCount: 31, unit: 'per pack', stock: 'instock', flag: 'Menthol', accent: 'var(--green-500)', image: 'assets/products/man-green.png' },
  { id: 'man-blue',     brand: 'Manchester', name: 'Blue Crush 6mc', cat: 'cigarettes', style: 'menthol', price: 39.95,                          rating: 4.8, ratingCount: 27, unit: 'per pack', stock: 'instock', flag: 'Menthol', accent: 'var(--blue-400)',  image: 'assets/products/man-blue.png' },
  { id: 'man-light',    brand: 'Manchester', name: 'Light 10mc',    cat: 'cigarettes', style: 'regular', price: 37.95,                          rating: 4.5, ratingCount: 9,  unit: 'per pack', stock: 'instock',                  accent: 'var(--cream-400)', image: 'assets/products/man-light.png' },
  { id: 'man-double',   brand: 'Manchester', name: 'Double Drive',  cat: 'cigarettes', style: 'menthol', price: 41.95, oldPrice: 47.95, discount: '12% OFF', rating: 4.9, ratingCount: 21, unit: 'per pack', stock: 'instock', flag: 'Dual menthol', accent: 'var(--blue-400)', image: 'assets/products/man-double-drive.png' },
  { id: 'sevenstars',   brand: 'Seven Stars', name: 'Charcoal Filter 10', cat: 'cigarettes', style: 'regular', price: 46.95,            rating: 4.9, ratingCount: 17, unit: 'per pack', stock: 'instock', flag: 'Japan', accent: 'var(--gold-400)', image: 'assets/products/sevenstars.png' },
];
